kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.ReplicaNumber }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      volumes:
        - name: index-html
          configMap:
            name: '{{ .Chart.Name }}-html'
            defaultMode: 420
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.containers.image }}:{{ .Values.containers.tag }}
          imagePullPolicy: Always
          env:
            - name: PORT
              value: {{ .Values.containers.containerPort | quote }}
          ports:
            - containerPort: {{ .Values.containers.containerPort }}
              protocol: TCP
          resources: {}
          readinessProbe:
            httpGet:
              path: /health/readiness # checks the application readiness URL path
              port: {{ .Values.containers.containerPort }} # port the application is listening on
              scheme: HTTP
            initialDelaySeconds: 1 # time to wait before first readiness check
            timeoutSeconds: 1 # readiness probe timeout
            periodSeconds: 10 # time between readiness checks
            successThreshold: 1 # required consecutive successes
            failureThreshold: 3 # consecutive failures before marking as unhealthy
          livenessProbe:
            httpGet:
              path: /health/liveliness # checks the application liveness URL path
              port: {{ .Values.containers.containerPort }} # port the application is listening on
              scheme: HTTP
            initialDelaySeconds: 1 # time to wait before first liveness check
            timeoutSeconds: 1 # liveness probe timeout
            periodSeconds: 10 # time between liveness checks
            successThreshold: 1 # required consecutive successes
            failureThreshold: 3 # consecutive failures before restart
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - name: index-html
              mountPath: /tmp/html # mounts the html.index file to its application location
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10